package com.tt.sabamiso.domain;

import java.util.Date;

import com.tt.sabamiso.framework.core.domain.BaseDomain;

public class File extends 
BaseDomain {
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column file.id
     * @mbggenerated
     */
    private Integer id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column file.name
     * @mbggenerated
     */
    private String name;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column file.content_type
     * @mbggenerated
     */
    private String contentType;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column file.size
     * @mbggenerated
     */
    private Long size;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column file.entry_date
     * @mbggenerated
     */
    private Date entryDate;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column file.update_date
     * @mbggenerated
     */
    private Date updateDate;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column file.id
     * @return  the value of file.id
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column file.id
     * @param id  the value for file.id
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column file.name
     * @return  the value of file.name
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column file.name
     * @param name  the value for file.name
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column file.content_type
     * @return  the value of file.content_type
     * @mbggenerated
     */
    public String getContentType() {
        return contentType;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column file.content_type
     * @param contentType  the value for file.content_type
     * @mbggenerated
     */
    public void setContentType(String contentType) {
        this.contentType = contentType == null ? null : contentType.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column file.size
     * @return  the value of file.size
     * @mbggenerated
     */
    public Long getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column file.size
     * @param size  the value for file.size
     * @mbggenerated
     */
    public void setSize(Long size) {
        this.size = size;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column file.entry_date
     * @return  the value of file.entry_date
     * @mbggenerated
     */
    public Date getEntryDate() {
        return entryDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column file.entry_date
     * @param entryDate  the value for file.entry_date
     * @mbggenerated
     */
    public void setEntryDate(Date entryDate) {
        this.entryDate = entryDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column file.update_date
     * @return  the value of file.update_date
     * @mbggenerated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column file.update_date
     * @param updateDate  the value for file.update_date
     * @mbggenerated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /** serialVersionUID */
    private static final long serialVersionUID = 7947870337753542206L;
}