/*-
 * Copyright (c) 2004-2014 GMO-RESEARCH Inc. All rights reserved.
 * Redistribution in source and binary forms, with or without
 * modification, is limited by contract. 
 */
package com.tt.sabamiso.domain;

import java.util.Date;

import javax.validation.constraints.NotNull;

import org.hibernate.validator.constraints.Email;
import org.hibernate.validator.constraints.NotEmpty;

import com.tt.sabamiso.framework.core.domain.BaseDomain;

/**
 * User model
 * @author usr160056
 * @since 2014/01/23
 */
public class User extends 



BaseDomain {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column users.user_id
     * @mbggenerated
     */
    private Integer userId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column users.user_name
     * @mbggenerated
     */
    @NotEmpty
    @Email
    private String userName;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column users.password
     * @mbggenerated
     */
    @NotEmpty
    private String password;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column users.company_id
     * @mbggenerated
     */
    @NotNull
    private Integer companyId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column users.nickname
     * @mbggenerated
     */
    @NotEmpty
    private String nickname;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column users.enabled
     * @mbggenerated
     */
    private Boolean enabled;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column users.entry_date
     * @mbggenerated
     */
    private Date entryDate;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column users.update_date
     * @mbggenerated
     */
    private Date updateDate;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column users.user_id
     * @return  the value of users.user_id
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column users.user_id
     * @param userId  the value for users.user_id
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column users.user_name
     * @return  the value of users.user_name
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column users.user_name
     * @param userName  the value for users.user_name
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column users.password
     * @return  the value of users.password
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column users.password
     * @param password  the value for users.password
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column users.company_id
     * @return  the value of users.company_id
     * @mbggenerated
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column users.company_id
     * @param companyId  the value for users.company_id
     * @mbggenerated
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column users.nickname
     * @return  the value of users.nickname
     * @mbggenerated
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column users.nickname
     * @param nickname  the value for users.nickname
     * @mbggenerated
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column users.enabled
     * @return  the value of users.enabled
     * @mbggenerated
     */
    public Boolean getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column users.enabled
     * @param enabled  the value for users.enabled
     * @mbggenerated
     */
    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column users.entry_date
     * @return  the value of users.entry_date
     * @mbggenerated
     */
    public Date getEntryDate() {
        return entryDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column users.entry_date
     * @param entryDate  the value for users.entry_date
     * @mbggenerated
     */
    public void setEntryDate(Date entryDate) {
        this.entryDate = entryDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column users.update_date
     * @return  the value of users.update_date
     * @mbggenerated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column users.update_date
     * @param updateDate  the value for users.update_date
     * @mbggenerated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /** serialVersionUID */
    private static final long serialVersionUID = 6234766547894600200L;
}